name: ci
on: [push]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Set up DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.0

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage:ci

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tag Release
      #   run: npx semantic-release
      #   if: github.ref == 'refs/heads/main'
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automaticaly set by Github